FROM tensorflow/tensorflow:latest-gpu-jupyter

# v1.0
RUN pip3 install pandas
RUN pip3 install seaborn
RUN pip3 install -U scikit-learn
RUN pip3 install auto-sklearn

# v1.1
RUN pip3 install crossref-commons
RUN pip3 install crossrefapi
RUN pip3 install habanero
RUN pip3 install openai
RUN pip3 install langchain[llms]
RUN pip3 install chromadb
RUN pip3 install llama-index
