FROM datascience:1.0

RUN pip3 install crossref-commons
RUN pip3 install crossrefapi
RUN pip3 install habanero
RUN pip3 install openai
RUN pip3 install llama-index
RUN pip3 install chromadb
RUN pip3 install langchain[llms]
